### ISSUE TITLE
Multiple free() bug in StreamCryptor.swift

### ISSUE THREAD

**Issue by carlbrown** [IBM-Swift/BlueCryptor#11]
With a long-lived Kitura processes using encrypted cookies, StreamCryptors get created and torn down many times as requests come in.

As per http://openssl.6102.n7.nabble.com/Multiple-calls-to-ERR-load-crypto-string-td4591.html `ERR_free_strings()` cannot be safely called in between calls to `ERR_load_crypto_strings()` without causing memory corruption.

More info (and full stack trace) at https://github.com/IBM-Swift/sandbox-ui/issues/119

Shortened stack trace:
[REDACTEDCrash.txt](https://github.com/IBM-Swift/BlueCryptor/files/565238/REDACTEDCrash.txt)

**Comment by billabt** [comment]
Fixed in the latest release.
