### ISSUE TITLE
HMAC-SHA1 Linux compatibility

### ISSUE THREAD

**Issue by collinhundley** [IBM-Swift/BlueCryptor#2]
The docs here say that HMAC-SHA1 is not supported by OpenSSL. However, as far as I can see it *does* appear to be supported (Ubuntu 16.04):

```sh
echo -n "value" | openssl dgst -sha1 -hmac "key"
>> 57443a4c052350a44638835d64fd66822f813319
```

Am I missing something? It would be great to use this for OAuth1. Thanks.

**Comment by billabt** [comment]
I can take a look. We haven't  tested much on 16.04 yet. If it can be supported, I'd like to get it added. If you're interested in taking a crack at it, I'd love to see a PR for it. But, remember, it's still got to work on Ubuntu 14.04 and 15.10 as well. These are the only versions that are "officially" supported right now.

**Comment by billabt** [comment]
I've added support for `SHA1` in both `Digest` and `HMAC` in release *0.5.4*.  Not really sure why I left them out in the first place.  My bad.  However, the restriction on `Digest` for `MD2` is still in place. Thanks Collin for pointing this out to me.

**Comment by collinhundley** [comment]
Awesome to hear. Thanks @billabt!
