### ISSUE TITLE
Please add ECDSA support for iCloud server-server auth

### ISSUE THREAD

**Issue by benspratling4** [IBM-Swift/BlueCryptor#21]
Apple's docs for iCloud server-to-server auth require the use of a "ECDSA signature".  Please add this capability.
https://developer.apple.com/library/content/documentation/DataManagement/Conceptual/CloudKitWebServicesReference/SettingUpWebServices/SettingUpWebServices.html#//apple_ref/doc/uid/TP40015240-CH24-SW6

**Comment by billabt** [comment]
There's another framework that I'm working on that will do what you want.  It's just not ready yet.  I've still got to add _Linux_ support to it.  I'll leave this issue open until it's released and then let you know.

**Comment by billabt** [comment]
Take a look at **BlueRSA**.  That framework should have what you’re looking for. Reopen (or open an issue against BlueRSA) if it doesn’t suit your needs.
