### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by AndrewSelvia** [IBM-Swift/BlueCryptor#22]
Hi @billabt Thanks for assembling this fantastic framework!

I'm using it on Linux fine. I now want to integrate it into my iOS app. iOS support is listed on the README, but integration is proving difficult. The Xcode project in the git repo seems to be configured for macOS; it produces a dylib. I have not yet succeeded at getting this dylib to build my iOS app which depends on `Cryptor`. Can you confirm that this project actually supports iOS integration? Do you have a sample iOS project that I can reference?

**Comment by billabt** [comment]
I added an iOS target to the Xcode project included in the project.  Use the _target Cryptor-iOS_ and it will build an iOS framework.  Let me know if you have any issues.  Thanks.
