### ISSUE TITLE
Error on import Cryptor using Swift 4 on Linux

### ISSUE THREAD

**Issue by billymeltdown** [IBM-Swift/BlueCryptor#24]
Hi there,

This is likely operator error, but I didn't see any tickets related and thought I'd see if I'm doing something obviously wrong. I'm trying to use the Cryptor package via Swift package manager for a command line executable on Ubuntu 16.04 using `swift-4.0-DEVELOPMENT-SNAPSHOT-2017-07-24-a-ubuntu16.04`, but I can't seem to get the package dependency  to take.

I set things up like so:

    mkdir rando
    cd rando
    swift package init --type executable

The Package.swift file for my new project:

```
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "rando",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/IBM-Swift/BlueCryptor.git", from: "0.8.16")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "rando",
            dependencies: []),
    ]
)
```

The main.swift file head:

    import Glibc
    import Foundation
    import Cryptor

When I run `swift build` things appear to go as planned but the compiler errors out on the import statement:

```
wgray@ubuntu:~/Swift/rando$ swift build
Fetching https://github.com/IBM-Swift/BlueCryptor.git
Updating https://github.com/IBM-Swift/BlueCryptor
Updating https://github.com/IBM-Swift/OpenSSL.git
Cloning https://github.com/IBM-Swift/BlueCryptor.git
Resolving https://github.com/IBM-Swift/BlueCryptor.git at 0.8.16
Compile Swift Module 'rando' (1 sources)
/home/wgray/Swift/rando/Sources/rando/main.swift:3:8: error: no such module 'Cryptor'
import Cryptor
       ^
error: terminated(1): /home/wgray/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-07-24-a-ubuntu16.04/usr/bin/swift-build-tool -f /home/wgray/Swift/rando/.build/debug.yaml main
```

Perhaps I missed a step, or need to provide some kind of module map listing? Another thought that occurs is that I've had to provide flags to the compiler and linker in other situations, am I missing something I should be passing, e.g. `swift build -Xcc -DENABLE_FOO` ?

Thanks for any advice, and apologies if there is another more preferable place to post questions like this.

**Comment by magiclee203** [comment]
I met the same issue and can't find a way to handle it.
I change the swift-tools-version to 3.1.1 and edit the Package.swift in an old Swift 3 way. 
This method is only a workaround but not the final solution.

**Comment by quanvo87** [comment]
After declaring a dependency, you also have to add its product name to depending targets' `dependencies` array. `BlueCryptor`'s product name is `Cryptor`.

This `Package.swift` file worked for me (using the optional `.upToNextMajor(from:)` syntax:

```
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "tmp",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "tmp",
            targets: ["tmp"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/IBM-Swift/BlueCryptor.git", .upToNextMajor(from: "0.0.0"))
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "tmp",
            dependencies: ["Cryptor"]),
        .testTarget(
            name: "tmpTests",
            dependencies: ["tmp"]),
    ]
)
```

**Comment by billabt** [comment]
I assume the recommended change above worked?  If not, feel free to re-open the issue.
