### ISSUE TITLE
The manifest file at https://github.com/IBM-Swift/CommonCrypto.git (0.1.3) is empty

### ISSUE THREAD

**Issue by carlhung** [IBM-Swift/BlueCryptor#27]
I got this error:

error: manifest parse error(s):
The manifest file at https://github.com/IBM-Swift/CommonCrypto.git (0.1.3) is empty

**Comment by billabt** [comment]
Try doing a package update.  The latest version is 0.1.5, not 0.1.3.  I suspect that you've got an older version in your build tree.  This is what happened when I tried it here...

```
Bills-Development-Mac-Pro:BlueCryptor babt$ rm -rf .build/
Bills-Development-Mac-Pro:BlueCryptor babt$ swift build
Fetching https://github.com/IBM-Swift/CommonCrypto.git
Fetching https://github.com/IBM-Swift/OpenSSL.git
Cloning https://github.com/IBM-Swift/OpenSSL.git
Resolving https://github.com/IBM-Swift/OpenSSL.git at 0.3.7
Cloning https://github.com/IBM-Swift/CommonCrypto.git
Resolving https://github.com/IBM-Swift/CommonCrypto.git at 0.1.5
Compile Swift Module 'Cryptor' (10 sources)
```
As you can see, it picked up version 0.1.5 which is the proper version to be using.  An' it builds cleanly.

If that doesn't work for you, feel free to re-open this issue.  Hope this solves it for you.

**Comment by krzyzanowskim** [comment]
That doesn't work for me and this one https://github.com/IBM-Swift/BlueCryptor/issues/29
The problem is with dependency chain in Kitura.
