### ISSUE TITLE
error: manifest parse error(s): The manifest file at https://github.com/IBM-Swift/CommonCrypto.git (0.1.3) is empty

### ISSUE THREAD

**Issue by carlhung** [IBM-Swift/BlueCryptor#28]
I cleaned up the last build. the following is my package.swift

let package = Package(
    name: "openActivity",
    dependencies: [
        .package(url: "https://github.com/IBM-Swift/Kitura.git", .upToNextMinor(from: "2.0.0")),
        .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", .upToNextMajor(from: "1.0.0")),
        .package(url: "https://github.com/IBM-Swift/BlueCryptor.git", .upToNextMajor(from: "0.8.0")),
        .package(url: "https://github.com/IBM-Swift/Kitura-Session.git", .upToNextMinor(from: "2.0.0")),
        .package(url: "https://github.com/IBM-Swift/Swift-Kuery.git", .upToNextMajor(from: "1.0.0")),
        .package(url: "https://github.com/IBM-Swift/SwiftKueryMySQL.git", .upToNextMajor(from: "1.0.0")),
    ],
    targets: [
        .target(
            name: "openActivity",
            dependencies: ["Kitura", "KituraSession", "HeliumLogger", "Cryptor", "SwiftKuery", "SwiftKueryMySQL" ]),
    ]
)

but I still get the same error:
error: manifest parse error(s): The manifest file at https://github.com/IBM-Swift/CommonCrypto.git (0.1.3) is empty

**Comment by billabt** [comment]
Try switching from 
```
.package(url: "https://github.com/IBM-Swift/BlueCryptor.git", .upToNextMajor(from: "0.8.0")),
```
to this
```
.package(url: "https://github.com/IBM-Swift/BlueCryptor.git", .upToNextMinor(from: "0.8.0")),
```

That's what _Kitura-Session_ is using and its having no problems...  Re-open if this doesn't work for you.  Thanks.
