### ISSUE TITLE
error: manifest parse error(s): The manifest file at https://github.com/IBM-Swift/CommonCrypto.git (0.1.3) is empty

### ISSUE THREAD

**Issue by carlhung** [IBM-Swift/BlueCryptor#29]
the version of swift is 4.0.3, on macOS(4.0.3) it returns the error message, on linux(4.0.3) it is just stuck while downloading dependencies. there is the whole file of package.swift:

    // swift-tools-version:4.0
    // The swift-tools-version declares the minimum version of Swift required to build this package.

    import PackageDescription

    let package = Package(
        name: "openActivity",
        dependencies: [
            .package(url: "https://github.com/IBM-Swift/Kitura.git", .upToNextMinor(from: "2.0.0")),
            .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", .upToNextMinor(from: "1.7.1")),
            .package(url: "https://github.com/IBM-Swift/Kitura-Session.git", .upToNextMinor(from: "2.0.0")),
            .package(url: "https://github.com/IBM-Swift/Swift-Kuery.git", .upToNextMajor(from: "1.0.0")),
            .package(url: "https://github.com/IBM-Swift/SwiftKueryMySQL.git", .upToNextMajor(from: "1.0.0")),
        ],
        targets: [
            .target(
                name: "openActivity",
                dependencies: ["Kitura", "HeliumLogger", "KituraSession", "SwiftKuery", "SwiftKueryMySQL"]),
        ]
    )

**Comment by krzyzanowskim** [comment]
The problem is with dependency chain, so far I found I had to "fix" these repos manually (if that help you)

.package(url: "https://github.com/krzyzanowskim/Kitura-Session", .branch("master")),
.package(url: "https://github.com/krzyzanowskim/Kitura-Credentials.git", .branch("master")),
.package(url: "https://github.com/krzyzanowskim/Kitura-CredentialsGitHub.git", .branch("master"))

**Comment by billabt** [comment]
Can you open an issue against _Kitura_ for this problem?  The problem appears to be with its' dependency chain.  In normal operation with other apps, I haven't been able to reproduce the problem.  Thanks.

**Comment by billabt** [comment]
Not a _BlueCryptor_ issue.  This issue related to dependency chain issues in *Kitura*.
