### ISSUE TITLE
ios/watchos/tvos support?

### ISSUE THREAD

**Issue by ratranqu** [IBM-Swift/BlueCryptor#3]
any thoughts on eventual ios/watchos/tvos support?

**Comment by billabt** [comment]
There should be no issues using this framework on any of those platforms.  For those platforms, the only thing required is `CommonCrypto` which I believe is available.

**Comment by ratranqu** [comment]
Could you update Package.swift please? :)
Happy to provide a PR as well, but might be overkill?

**Comment by billabt** [comment]
Sure, I'll add it right now.  Thanks.  PR would probably be overkill. 😃

**Comment by ratranqu** [comment]
awesome. thx very much for lightning fast turnaround :).

**Comment by billabt** [comment]
Done.  You should be all set.

**Comment by ratranqu** [comment]
thx!
