### ISSUE TITLE
Replace some fatalError's by optional/Result/throws

### ISSUE THREAD

**Issue by mbrandonw** [IBM-Swift/BlueCryptor#30]
I'm using `Cryptor` for doing signed+encrypted cookies, as well as encrypted values in url params, for example an unsubscribe link in an email that allows quick removal from newsletters.

The library currently `fatalError`'s _a lot_. Some of it seems reasonable, like using an unsupported encryption algorithm. However, `fatalError`'s are also used for malformed data, which could happen if the user tampers with cookies, urls, etc... This means a user can crash a server using `Cryptor` very easily.

Should all uses of `fatalError` be audited to convert most to use optionals, `Result` or `throws`?

**Comment by billabt** [comment]
I totally agree with you.  I've had that on my todo list for a bit now but haven't had the chance to get to it.  Now that I'm _retired_, I've got a lot more time to spend on it and will try to get to it sooner rather than later.

**Comment by mbrandonw** [comment]
Hi @billabt, that's great to hear!

**Comment by billabt** [comment]
Hi @mbrandonw.  I'm starting the audit now on the code.  It's going to result in quite a few _source breaking changes_ and is probably going to take a little bit of time to get right.  In the meantime, the library does have a mechanism for catching those **fatalErrors**.  Take a look a _Utilities.swift_.  Right near the top you'll see an override of the _fatalError()_ function.  Following that, you'll see the _FatalErrorUtil_ struct.  There's a function in that struct that allows you to override the behavior when a _fatalError_ is called.  You can call _FatalErrorUtil.replaceFatalError()_ giving it your own flavor of error handling.  This might help you in the short term until the library changes are complete.

**Comment by billabt** [comment]
Changes completed in _Version 1.0.0_.  Let me know what you think.
