### ISSUE TITLE
CMS Signatures

### ISSUE THREAD

**Issue by sdnakhla** [IBM-Swift/BlueCryptor#36]
Would it be possible to get CMS/PKCS#7 signatures (both attached and detached) added to BlueCrypto?  This would be useful for signing MDM payloads, validating AppStore receipts, etc.  It's also unsupported by any Swift Linux framework.

**Comment by billabt** [comment]
This will eventually be added to [BlueRSA](https://github.com/IBM-Swift/BlueRSA.git).  Please open an enhancement request against this project so that it doesn't get lost between the cracks.  Thanks.
