### ISSUE TITLE
Cryptor-iOS Scheme is not Shared

### ISSUE THREAD

**Issue by jracc** [IBM-Swift/BlueCryptor#43]
Because the scheme is not shared, I cannot do a build with Carthage.  Would you mind making sure the scheme is shared as are the other two?

**Comment by billabt** [comment]
No PR necessary. I can fix it in a few minutes. 😉

**Comment by billabt** [comment]
Fixed in _version 1.0.6_.

**Comment by jracc** [comment]
Awesome.  Thank-you.

- cjm
