### ISSUE TITLE
Updating with Data

### ISSUE THREAD

**Issue by collinhundley** [IBM-Swift/BlueCryptor#7]
Line 65 of Updatable.swift - is there any reason `data` needs to be `inout`?

```swift
public func update(data: inout Data) -> Self? 
```

It makes this method unusable with immutable `Data` objects. The pointer generated in the closure is immutable so I don't see a reason to force the `inout` argument.

**Comment by billabt** [comment]
I'll take a look. You might be right.

**Comment by billabt** [comment]
You were right.  Corrected in the latest release.  Thanks.
